"""Create tables

Revision ID: 56fa797b055e
Revises: 
Create Date: 2025-02-10 23:58:10.280833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fa797b055e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('quotes_names', sa.String(), nullable=True),
    sa.Column('orcid', sa.String(), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('professional_institution', sa.String(), nullable=True),
    sa.Column('institution_state', sa.String(), nullable=True),
    sa.Column('institution_city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_background',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_experience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('employment_relationship', sa.String(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('major_knowledge_area', sa.String(), nullable=False),
    sa.Column('knowledge_area', sa.String(), nullable=False),
    sa.Column('sub_knowledge_area', sa.String(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('major_knowledge_area', sa.String(), nullable=False),
    sa.Column('knowledge_area', sa.String(), nullable=False),
    sa.Column('sub_knowledge_area', sa.String(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('academic_background_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_background_id'], ['academic_background.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_area')
    op.drop_table('research_area')
    op.drop_table('professional_experience')
    op.drop_table('academic_background')
    op.drop_table('researcher')
    # ### end Alembic commands ###
