from typing import Protocol


class Filters(Protocol):
    def countries(self) -> list[str]: ...
    def states(self) -> list[str]: ...
    def titles(self) -> list[str]: ...
    def expertises(self) -> list[str]: ...
