from typing import Protocol, Sequence


class Filters(Protocol):
    def countries(self) -> Sequence[str]: ...
    def states(self) -> Sequence[str]: ...
    def titles(self) -> Sequence[str]: ...
    def expertises(self) -> Sequence[str]: ...


@attrs.frozen
class FiltersInDatabase:
    database: Database

    def countries(self) -> list[str]:
        with self.database.session as session:
            return session.exec(
                select(tables.Address.country).distinct(),
            ).all()

    def states(self) -> list[str]: ...
    def titles(self) -> list[str]: ...
    def expertises(self) -> list[str]: ...
