"""Add unique constraints

Revision ID: 7599779f6036
Revises: 56fa797b055e
Create Date: 2025-02-13 16:51:56.217313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7599779f6036"
down_revision: Union[str, None] = "56fa797b055e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_academic_background",
        "academic_background",
        [
            "type",
            "institution",
            "course",
            "start_year",
            "end_year",
            "researcher_id",
        ],
    )
    op.create_unique_constraint(
        "unique_knowledge_area",
        "knowledge_area",
        [
            "major_knowledge_area",
            "knowledge_area",
            "sub_knowledge_area",
            "specialty",
            "academic_background_id",
        ],
    )
    op.create_unique_constraint(
        "unique_professional_experience",
        "professional_experience",
        [
            "institution",
            "employment_relationship",
            "start_year",
            "end_year",
            "researcher_id",
        ],
    )
    op.create_unique_constraint(
        "unique_research_area",
        "research_area",
        [
            "major_knowledge_area",
            "knowledge_area",
            "sub_knowledge_area",
            "specialty",
            "researcher_id",
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
