from pathlib import Path
from typing import Literal

import cyclopts

from src.shared import database, vitae

from . import scanners
from .repository import Researchers
from .usecase import Ingestion

__all__ = ["app"]

app = cyclopts.App(name="ingest")


_strategy = {
    "serial": scanners.serial,
    "pool": scanners.thread_pool,
}


@app.default
def ingest(
    # sub_folders: list[int] | None = None,
    strategy: Literal[tuple(_strategy)] = "pool",  # type: ignore[arg-type]
    buffer: int = 50,
    processed: Path = Path("logs/ingestion/processed.log"),
) -> None:
    """Ingest XML documents into the database.

    Parameters
    ----------
    strategy : Literal["serial", "pool"], default="pool"
        Method used to scan the directory containing XML files.
        Use "serial" for sequential scanning or "pool" for parallel scanning.

    buffer : int, default=50
        Number of researchers to buffer before committing to the database.
        Use higher numbers on production.

    processed : Path, default=Path("logs/ingestion/processed.log")
        Path to a log file (to be) generated by this application containing
        IDs of already processed files.
        On subsequent runs, files listed in this log will be skipped.

    """
    repository = Researchers(db=database, every=buffer)
    processed_curricula = curricula_xml_from(processed)

    ingestion = Ingestion(
        researchers=repository,
        scanner=strategy,
        files=vitae.paths.curricula,
        to_skip=processed_curricula,
    )

    ingestion.ingest()


# =~=~=~=~=~=~ Helper Functions ~=~=~=~=~=~=


def curricula_xml_from(log: Path) -> set[str]:
    """Load curricula from log file.

    Note:
    ----
    Its expected that each line contains only one Researcher's ID.

    Returns:
    -------
    All processed Curricula's ID into a set as `<id>.xml` strings.

    """
    with log.open("r") as file:
        result: set[str] = {line.strip("\n") + ".xml" for line in file}
    return result
