from sqlmodel import Field, Relationship, SQLModel


class Researcher(SQLModel, table=True):
    __tablename__: str = "researcher"

    id: str = Field(primary_key=True, nullable=False)
    # updated_at: str | None = Field(
    #     default=None, sa_column_kwargs={"default": "now()", "onupdate": "now()"}
    # )
    name: str = Field(nullable=False, index=True)
    city: str | None = None
    state: str | None = None
    country: str | None = None
    quotes_names: str | None = None
    orcid: str | None = None
    abstract: str | None = None
    professional_institution: str | None = None
    institution_state: str | None = None
    institution_city: str | None = None

    professional_experience: list["ProfessionalExperience"] = Relationship(
        back_populates="researcher",
    )
    academic_background: list["AcademicBackground"] = Relationship(
        back_populates="researcher",
    )
    research_area: list["ResearchArea"] = Relationship(
        back_populates="researcher",
    )


class ProfessionalExperience(SQLModel, table=True):
    __tablename__: str = "professional_experience"

    # Generated by Database
    id: int | None = Field(default=None, primary_key=True)

    # Owner
    researcher_id: str = Field(foreign_key="researcher.id")
    researcher: "Researcher" = Relationship(
        back_populates="professional_experience",
    )

    # Data
    institution: str = Field(nullable=False, index=True)
    employment_relationship: str | None = None
    start_year: int | None = None
    end_year: int | None = None


class AcademicBackground(SQLModel, table=True):
    __tablename__: str = "academic_background"
    id: int | None = Field(default=None, primary_key=True)

    # Owner
    researcher_id: str = Field(foreign_key="researcher.id")
    researcher: "Researcher" = Relationship(
        back_populates="academic_background",
    )

    # Data
    type: str
    institution: str
    course: str | None = None
    start_year: int | None = None
    end_year: int | None = None


class KnowledgeArea(SQLModel, table=True):
    __tablename__: str = "knowledge_area"

    # Database Generated
    id: int | None = Field(default=None, primary_key=True)

    # Owner
    academic_background_id: int = Field(foreign_key="academic_background.id")

    major_knowledge_area: str
    knowledge_area: str | None = None
    sub_knowledge_area: str | None = None
    specialty: str | None = None


class ResearchArea(SQLModel, table=True):
    __tablename__: str = "research_area"

    # Database generated
    id: int | None = Field(default=None, primary_key=True)

    # Owner
    researcher_id: str = Field(foreign_key="researcher.id")
    researcher: "Researcher" = Relationship(
        back_populates="research_area",
    )

    major_knowledge_area: str
    knowledge_area: str | None = None
    sub_knowledge_area: str | None = None
    specialty: str | None = None
